languages: node_js
node_js: -10.15.3
cache: npm

install:
  - npm install

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages
